package GUI;

import auctionsystem.Sys;
import auctionsystem.User;
import Validation.Validation;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author emad
 */
public class Register extends javax.swing.JInternalFrame {

    /**
     * Creates new form Register
     */
    public Register() {
        initComponents();
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        this.Question.removeAllItems();
        this.Countries.removeAllItems();
            ArrayList<String> arr = Sys.GetSystem().GetAllCountry();        
        for(int i=0;i<arr.size();i++)
        {               
            Countries.addItem(arr.get(i));
        }
        arr=Sys.GetSystem().GetAllQuestions();
        for(int i=0;i<arr.size();i++)
        {
            Question.addItem(arr.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MyGroup = new javax.swing.ButtonGroup();
        Area = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FNAME = new javax.swing.JTextField();
        LNAME = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Answer = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Bidder = new javax.swing.JRadioButton();
        Seller_ = new javax.swing.JRadioButton();
        Question = new javax.swing.JComboBox<>();
        Pass = new javax.swing.JPasswordField();
        Countries = new javax.swing.JComboBox<>();
        Country = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(670, 501));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 204));
        jLabel1.setText("Fname");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 73, 87, -1));

        jLabel2.setBackground(new java.awt.Color(51, 255, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Registeration From");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(254, 26, 273, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 204, 204));
        jLabel3.setText("Lname");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 108, 87, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 204, 204));
        jLabel4.setText("Email");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 143, 81, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 178, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 204, 204));
        jLabel6.setText("Question");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 211, 87, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 204));
        jLabel7.setText("Answer");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 247, 87, -1));

        FNAME.setBackground(new java.awt.Color(204, 204, 204));
        FNAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(FNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 74, 251, -1));

        LNAME.setBackground(new java.awt.Color(204, 204, 204));
        LNAME.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(LNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 109, 251, -1));

        Email.setBackground(new java.awt.Color(204, 204, 204));
        Email.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 144, 251, -1));

        Answer.setBackground(new java.awt.Color(204, 204, 204));
        Answer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel1.add(Answer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 248, 251, -1));

        jButton1.setBackground(new java.awt.Color(102, 255, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Submit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 431, 114, -1));

        Bidder.setBackground(new java.awt.Color(102, 102, 102));
        MyGroup.add(Bidder);
        Bidder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Bidder.setForeground(new java.awt.Color(255, 255, 255));
        Bidder.setText("Bidder");
        jPanel1.add(Bidder, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 367, -1, -1));

        Seller_.setBackground(new java.awt.Color(102, 102, 102));
        MyGroup.add(Seller_);
        Seller_.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Seller_.setForeground(new java.awt.Color(255, 255, 255));
        Seller_.setText("Seller");
        jPanel1.add(Seller_, new org.netbeans.lib.awtextra.AbsoluteConstraints(504, 367, -1, -1));

        Question.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Question, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 214, 251, 22));

        Pass.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.add(Pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 178, 251, -1));

        Countries.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(Countries, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 292, 251, 22));

        Country.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        Country.setForeground(new java.awt.Color(0, 204, 204));
        Country.setText("Country");
        jPanel1.add(Country, new org.netbeans.lib.awtextra.AbsoluteConstraints(156, 289, 87, -1));

        javax.swing.GroupLayout AreaLayout = new javax.swing.GroupLayout(Area);
        Area.setLayout(AreaLayout);
        AreaLayout.setHorizontalGroup(
            AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AreaLayout.setVerticalGroup(
            AreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Area, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Sys s = Sys.GetSystem();
        Validation V=Validation.Get_Validation_Instance();
        boolean Flag = true;
        char pass[] = this.Pass.getPassword();
        String Password = "";
        for (int i = 0; i < pass.length; i++) {
            Password += pass[i];
        }
        try 
        {
            int Type;
            String FNAME = this.FNAME.getText();
            String LNAME = this.LNAME.getText();
            float Balance = 0;
            String Mail = this.Email.getText();
            String Password_ = Password;
            String SequrityQuestion = this.Question.getSelectedItem().toString();
            String AnswerQuestion = this.Answer.getText();
            String Country = this.Countries.getSelectedItem().toString();
            Type=-1;
            if (this.Bidder.isSelected()) 
            {
                 Type = 4;
            }
            else if(this.Seller_.isSelected())
            {
                 Type = 5;
            }
            if(V.Is_Password(Password_))
            {
            if(V.Is_Name(FNAME)&&V.Is_Name(LNAME)&&V.Is_Emil(Mail)&&Type!=-1)
            {
                      User U = new User();
                      U.Type=Type;
                      U.FNAME=FNAME;
                      U.LNAME=LNAME;
                      U.login.Mail=Mail;
                      U.login.Password=Password_;
                      U.Country=Country;
                      U.login.SequrityQuestion=SequrityQuestion;
                      U.login.AnswerQuestion=AnswerQuestion;
                      U.Balance=Balance;
                      s.Regist(U);
            JOptionPane.showMessageDialog(null, "Done");                      
            }
            else
            {
            JOptionPane.showMessageDialog(null, "Invalid Data");
            }
            }
            else
            {
            JOptionPane.showMessageDialog(null, "Invalid Password"+System.lineSeparator()+"at least 8 char have 1 digit and 2 char at least");
            this.Pass.setBackground(Color.red);
            }
            

        } 
        catch (Exception E)
        {
            JOptionPane.showMessageDialog(null, "Invalid Data");
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer;
    private javax.swing.JPanel Area;
    private javax.swing.JRadioButton Bidder;
    private javax.swing.JComboBox<String> Countries;
    private javax.swing.JLabel Country;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField FNAME;
    private javax.swing.JTextField LNAME;
    private javax.swing.ButtonGroup MyGroup;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JComboBox<String> Question;
    private javax.swing.JRadioButton Seller_;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
