/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;


import java.util.HashMap;

/**
 *
 * @author emad
 */
public class SearchDept extends javax.swing.JInternalFrame {

    /**
     * Creates new form DeptSearch
     */
    
    public SearchDept(HashMap<String,String> D) {
      ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);                                
        initComponents();
        int ID=Integer.parseInt(D.get("ID"));
        System.out.print(ID);
        if(ID>100&&ID<=200)
        {
            this.TCP.setText(D.get("CarSpeed"));
            this.MP.setText(D.get("MotorPower"));
            this.TNOP.setText(D.get("NumberOfPassengers"));
            
            this.BV.setVisible(false);
            this.SS.setVisible(false);
            this.T.setVisible(false);
            this.H.setVisible(false);
            this.P.setVisible(false);
            this.R.setVisible(false);
            
            this.TBV.setVisible(false);
            this.TSS.setVisible(false);
            this.TTS.setVisible(false);
            this.TH.setVisible(false);
            this.TP.setVisible(false);
            this.TR.setVisible(false);
        }
        else if(ID>200)
        {
            this.TBV.setText(D.get("BatteryVolt"));
            this.TSS.setText(D.get("ToatlSize"));
            this.CarSpeed.setVisible(false);
            this.H.setVisible(false);
            this.MP.setVisible(false);
            this.MotorPower.setVisible(false);
            this.NOP.setVisible(false);
            this.P.setVisible(false);
            this.R.setVisible(false);
            this.T.setVisible(false);
            
            this.TCP.setVisible(false);
            this.TTS.setVisible(false);
            this.TH.setVisible(false);
            this.TP.setVisible(false);
            this.TR.setVisible(false);
            this.TNOP.setVisible(false);
            this.MP.setVisible(false);
        }
        else
        {
            this.TH.setText(D.get("Hard"));
            this.TR.setText(D.get("Ram"));
            this.TSS.setText(D.get("ScreenSize"));
            this.TP.setText(D.get("Processor"));
            
            this.TNOP.setVisible(false);
            this.TCP.setVisible(false);
            this.MP.setVisible(false);
            this.TBV.setVisible(false);
            this.TTS.setVisible(false);
            
            this.MotorPower.setVisible(false);
            this.CarSpeed.setVisible(false);
            this.BV.setVisible(false);
            this.NOP.setVisible(false);
            this.TTS.setVisible(false);
            this.T.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MotorPower = new javax.swing.JLabel();
        NOP = new javax.swing.JLabel();
        CarSpeed = new javax.swing.JLabel();
        BV = new javax.swing.JLabel();
        T = new javax.swing.JLabel();
        R = new javax.swing.JLabel();
        H = new javax.swing.JLabel();
        SS = new javax.swing.JLabel();
        P = new javax.swing.JLabel();
        TCP = new javax.swing.JTextField();
        TNOP = new javax.swing.JTextField();
        MP = new javax.swing.JTextField();
        TSS = new javax.swing.JTextField();
        TBV = new javax.swing.JTextField();
        TP = new javax.swing.JTextField();
        TR = new javax.swing.JTextField();
        TH = new javax.swing.JTextField();
        TTS = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        MotorPower.setBackground(new java.awt.Color(51, 255, 51));
        MotorPower.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        MotorPower.setForeground(new java.awt.Color(0, 204, 204));
        MotorPower.setText("Motor Power :");

        NOP.setBackground(new java.awt.Color(51, 255, 51));
        NOP.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        NOP.setForeground(new java.awt.Color(0, 204, 204));
        NOP.setText("Number Of Passengers");

        CarSpeed.setBackground(new java.awt.Color(51, 255, 51));
        CarSpeed.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        CarSpeed.setForeground(new java.awt.Color(0, 204, 204));
        CarSpeed.setText("Car Speed :");

        BV.setBackground(new java.awt.Color(51, 255, 51));
        BV.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        BV.setForeground(new java.awt.Color(0, 204, 204));
        BV.setText("Battery Volt");

        T.setBackground(new java.awt.Color(51, 255, 51));
        T.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        T.setForeground(new java.awt.Color(0, 204, 204));
        T.setText("Total Size");

        R.setBackground(new java.awt.Color(51, 255, 51));
        R.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        R.setForeground(new java.awt.Color(0, 204, 204));
        R.setText("Ram");

        H.setBackground(new java.awt.Color(51, 255, 51));
        H.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        H.setForeground(new java.awt.Color(0, 204, 204));
        H.setText("Hard");

        SS.setBackground(new java.awt.Color(51, 255, 51));
        SS.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        SS.setForeground(new java.awt.Color(0, 204, 204));
        SS.setText("Screen Size");

        P.setBackground(new java.awt.Color(51, 255, 51));
        P.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        P.setForeground(new java.awt.Color(0, 204, 204));
        P.setText("Processor ");

        TCP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TNOP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        MP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TSS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TBV.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TP.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TR.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TH.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        TTS.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(SS, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 77, Short.MAX_VALUE)
                        .addComponent(TSS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(R, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TR, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(P, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(H, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TH, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BV, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TBV, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NOP, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TNOP, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(MotorPower, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(CarSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TCP, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(T, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TTS, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(32, 32, 32))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CarSpeed)
                                    .addComponent(TCP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(MotorPower))
                            .addComponent(MP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(NOP))
                    .addComponent(TNOP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BV)
                    .addComponent(TBV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(T)
                    .addComponent(TTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(H)
                    .addComponent(TH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(P)
                    .addComponent(TP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(R)
                    .addComponent(TR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SS))
                .addContainerGap(102, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BV;
    private javax.swing.JLabel CarSpeed;
    private javax.swing.JLabel H;
    private javax.swing.JTextField MP;
    private javax.swing.JLabel MotorPower;
    private javax.swing.JLabel NOP;
    private javax.swing.JLabel P;
    private javax.swing.JLabel R;
    private javax.swing.JLabel SS;
    private javax.swing.JLabel T;
    private javax.swing.JTextField TBV;
    private javax.swing.JTextField TCP;
    private javax.swing.JTextField TH;
    private javax.swing.JTextField TNOP;
    private javax.swing.JTextField TP;
    private javax.swing.JTextField TR;
    private javax.swing.JTextField TSS;
    private javax.swing.JTextField TTS;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
