/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.util.ArrayList;
import javax.swing.JLabel;

/**
 *
 * @author emad
 */
public class WaitItems extends javax.swing.JInternalFrame {

    /**
     * Creates new form WaitItems
     */
    ArrayList <Integer> More=null;
    public WaitItems(ArrayList<Integer> Info) {
        ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);        
        initComponents();
        ArrayList<JLabel> JLs=new ArrayList<JLabel>();
        JLs.add(L1);
        JLs.add(L2);
        JLs.add(L3);
        JLs.add(L4);
        JLs.add(L5);
        if(Info.size()>5)
        {
            More=new ArrayList<>();
            for(int i=5;i<Info.size();i++)
            {
                More.add(Info.get(i));
            }
            for(int i=0;i<5;i++)
            {
                JLs.get(i).setText(""+Info.get(i));
            }             
        }
        else
        {
            for(int i=0;i<Info.size();i++)
            {
                JLs.get(i).setText("Item "+Info.get(i)+" Is Waiting For Order");
            }               
            MoreButton.setVisible(false);
        }
               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        L3 = new javax.swing.JLabel();
        L4 = new javax.swing.JLabel();
        L5 = new javax.swing.JLabel();
        L2 = new javax.swing.JLabel();
        L1 = new javax.swing.JLabel();
        MoreButton = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setBackground(new java.awt.Color(51, 255, 51));
        jLabel2.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 255, 0));
        jLabel2.setText("Items In Wait Mood");

        L3.setBackground(new java.awt.Color(51, 51, 51));
        L3.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        L3.setForeground(new java.awt.Color(0, 255, 255));
        L3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        L3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        L4.setBackground(new java.awt.Color(51, 51, 51));
        L4.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        L4.setForeground(new java.awt.Color(0, 255, 255));
        L4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        L4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        L5.setBackground(new java.awt.Color(51, 51, 51));
        L5.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        L5.setForeground(new java.awt.Color(0, 255, 255));
        L5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        L5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        L2.setBackground(new java.awt.Color(51, 51, 51));
        L2.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        L2.setForeground(new java.awt.Color(0, 255, 255));
        L2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        L2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        L1.setBackground(new java.awt.Color(51, 51, 51));
        L1.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        L1.setForeground(new java.awt.Color(0, 255, 255));
        L1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        L1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        L1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        MoreButton.setBackground(new java.awt.Color(102, 255, 102));
        MoreButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        MoreButton.setText("More");
        MoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MoreButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(176, 176, 176)
                                .addComponent(MoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addComponent(L3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addComponent(L5, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addComponent(L2, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE)
                            .addComponent(L1, javax.swing.GroupLayout.DEFAULT_SIZE, 482, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(L1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(L5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(MoreButton, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MoreButtonActionPerformed
        ManagerHome.ManagerView.removeAll();
        ManagerHome.ManagerView.repaint();
        ManagerHome.ManagerView.revalidate();
        WaitItems S=new WaitItems(More);
        ManagerHome.ManagerView.add(S);
        S.setVisible(true);   
    }//GEN-LAST:event_MoreButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel L1;
    private javax.swing.JLabel L2;
    private javax.swing.JLabel L3;
    private javax.swing.JLabel L4;
    private javax.swing.JLabel L5;
    private javax.swing.JButton MoreButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
